name: Build and Release

on:
  push:
    branches:
      - ci/cd

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build application
        run: |
          pyinstaller SEOMaker.spec

      - name: Verify output
        run: |
          dir dist

      - name: Compress build folder
        run: |
          powershell Compress-Archive -Path dist/SEOMaker/* -DestinationPath SEOMaker.zip

      - name: Upload Release Artifact (EXE)
        uses: actions/upload-artifact@v3
        with:
          name: SEOMaker-EXE
          path: dist/SEOMaker/SEOMaker.exe

      - name: Upload Release Artifact (ZIP)
        uses: actions/upload-artifact@v3
        with:
          name: SEOMaker-Complete
          path: SEOMaker.zip

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            dist/SEOMaker/SEOMaker.exe
            SEOMaker.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v1.0.${{ github.run_number }}
          name: SEOMaker v1.0.${{ github.run_number }}
          body: |
            ### Changelog
            - Automated release created by GitHub Actions.
