name: Build and Release Python App

on:
  push:
    branches:
      - ci/cd

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build application
        run: |
          pyinstaller SEOMaker.spec

      - name: Verify output
        run: |
          dir dist

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v3
        with:
          name: PythonApp
          path: dist/SEOMaker.exe

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/SEOMaker.exe
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.run_number }}
          name: Release-${{ github.run_number }}
          body: |
            Release created automatically by GitHub Actions.
